version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  backend:
    build: ./backend
    container_name: express-backend
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydb
      - DB_PORT=5432
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb?schema=public
    restart: always

  frontend:
    build: ./frontend
    container_name: nuxt-frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app
    environment:
      - NUXT_API_BASE=backend:4000
    restart: always

volumes:
  pg_data:
